language: node_js
node_js:
  - "8"

cache:
  directories:
    - "node_modules"

install:
  - npm i truffle
  - npm i ethereumjs-testrpc

before_script: ./node_modules/ethereumjs-testrpc/build/cli.node.js &
script: ./node_modules/truffle/build/cli.bundled.js test