dist: trusty
language: node_js
node_js:
  - '7'
install:
  - npm install
script:
  - npm test
before_script:
  - testrpc -l 40000000 > /dev/null &
  - sleep 5
after_script:
  - npm run coverage && cat coverage/lcov.info | coveralls
