language: node_js
node_js:
  - "8"

cache:
  directories:
    - "node_modules"

install:
  - npm i truffle
  - npm i ethereumjs-testrpc

before_script: $(npm bin)/testrpc &
script: $(npm bin)/truffle test